### ISSUE TITLE
Release of Checkpoint

### ISSUE THREAD

**Issue by ldkong1205** [valeoai/WaffleIron#1]
Hi @anhquancao @gpuy @tristanschultz, thanks a lot for open-sourcing your work!

Regarding the reproduction, could you share with me the trained model weights on SemanticKITTI? Thanks for your help!

**Comment by gpuy** [comment]
Hi @ldkong1205,

Thanks for your interest in this work. Pretrained models are normally already available. For SemanticKITTI, you should be able to use the pretrained model directly with the following commands:
```
git clone https://github.com/valeoai/WaffleIron
cd WaffleIron
wget https://github.com/valeoai/WaffleIron/files/10294735/pretrained_kitti.tar.gz
tar -xvzf pretrained_kitti.tar.gz
```
Let me know if the link does not work for you.

**Comment by ldkong1205** [comment]
Hi @gpuy, thanks for your reply!

I have tested the links for downloading data_info, kitti_ckp, and nusc_ckp, and all of them are good. I will test their performance now to see if they can match the reported scores in the paper, and get to know more implementation of this work.

Thanks again for open-sourcing this insightful work!
