### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by SpeedyGonzales949** [valeoai/WaffleIron#11]
I am using python 3.10.14 and pytorch 1.11.0 with cudatoolkit 11.3.1. I am trying to train on a RTX 2080 TI using the following config:  
{
            "label": "Run Train on Nuscenes",
            "type": "process",
            "command":  "\\anaconda3\\envs\\WaffleIron\\python.exe",
            "args": [
                "launch_train.py",
                "--dataset", "nuscenes",
                "--path_dataset", ".\\data",
                "--log_path", ".\\logs\\WaffleIron-48-256__nuscenes\\",
                "--config", ".\\configs\\WaffleIron-48-256__nuscenes.yaml",
                "--fp16",
                "--multiprocessing-distributed",
                "--gpu", "0",
                "--restart"
            ]
        }
I get the following error:

Traceback (most recent call last):
  File "WaffleIron\launch_train.py", line 372, in <module>
    main(args, config)
  File "WaffleIron\launch_train.py", line 306, in main
    distributed_training(args.gpu, ngpus_per_node, args, config)
  File "WaffleIron\launch_train.py", line 253, in distributed_training
    mng.train()
  File "WaffleIron\utils\trainer.py", line 290, in train
    self.one_epoch(training=True)
  File "WaffleIron\utils\trainer.py", line 173, in one_epoch
    temp = out[id_b, :, closest_point]
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by gpuy** [comment]
Thank you. I accepted your pull request.
