### ISSUE TITLE
Semantic_kitti.yaml - content

### ISSUE THREAD

**Issue by GyoungTaeChae** [valeoai/WaffleIron#14]
Hello,

First of all, I truly appreciate the excellent work you're doing!

I'm currently working on training a custom dataset formatted like the KITTI dataset. As part of this process, I need to modify the some files. Could you please guide me how to change below part?

```
def test_loaded(self):
        self.__loaded__ = False
        if self.phase == "train":
            if len(self.bank[1]) != 5083:
                return False
            if len(self.bank[2]) != 3092:
                return False
            if len(self.bank[4]) != 7419:
                return False
            if len(self.bank[5]) != 8084:
                return False
            if len(self.bank[6]) != 1551:
                return False
        elif self.phase == "trainval":
            if len(self.bank[1]) != 8213:
                return False
            if len(self.bank[2]) != 4169:
                return False
            if len(self.bank[4]) != 10516:
                return False
            if len(self.bank[5]) != 12190:
                return False
            if len(self.bank[6]) != 2943:
                return False
        self.__loaded__ = True
        return True


```

Thank you in advance for your assistance. I look forward to your response!

**Comment by gpuy** [comment]
Hi,

Thank you for the positive comment!

This part is called only when applying instance cutmix as augmentation during training. 

This part of the code is specific to the official version of SemanticKITTI and, indeed, will break for other datasets if re-using the same dataloader. An example of dataloading without this augmentation is available in `nuscenes.py` .

In your case, the simplest should be to not apply instance cutmix augmentations by setting [`instance_cutmix`](https://github.com/valeoai/WaffleIron/blob/master/configs/WaffleIron-48-256__kitti.yaml#L45) to `False`. This function won't be called and then, hopefully, the rest of the code should run correctly.

Let me know if you need more details.

**Comment by GyoungTaeChae** [comment]
Thank you

I thoroughly reviewed the code and was able to identify and fix the issues on my own.(with my mistake, i missed your reply ...🥲)  Although it would have been easier with your advice, this was also a valuable experience. I was so happy when I successfully resolved the problem that I cheered in the lab.

Problem sovled.  You can close this issue.

**Comment by gpuy** [comment]
Good to see the problem is solved !
