### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by TengfeiZeng** [valeoai/WaffleIron#5]
Hello author, I would like to know what equipment you used for training and how long it took you to complete the training?

**Comment by gpuy** [comment]
Hi @TengfeiZeng,

We did the training using four RTX 2080 Ti.

Concerning training time:
- For WI-48-256, it was taking around 2 days on the train set of SemanticKITTI and 2.2 days on the train set of nuScenes.
- For WI-48-384, it tooks around 2.7 days on the train set of nuScenes.

In all cases, we trained the networks for 45 epochs and used the checkpoint at the last epoch to report the results.

Hope this helps.

Cheers,

Gilles
