### ISSUE TITLE
Could you please tell me how to get the results of semantickitti in the test set, thank you!

### ISSUE THREAD

**Issue by horizonfly99** [valeoai/WaffleIron#9]
Could you please tell me how to get the results of semantickitti in the test set, thank you!

**Comment by gpuy** [comment]
Dear @horizonfly99,

If your goal is to submit predictions of some models on the test set, you can use the script `eval_kitti.py` with the flag `--phase test`. This will save the prediction on disk. You can then zip the result folder and submit it to the benchmark. I let you read [here](https://github.com/PRBonn/semantic-kitti-api?tab=readme-ov-file#validation) how to validate the zip folder before submission and [here](https://codalab.lisn.upsaclay.fr/competitions/6280#learn_the_details) about the submission process itself.

If your goal is to reproduce our results on the test set then you will need to retrain a model using both the training and validation splits, and also use test time augmentation to obtain the predictions. We provide the details in our paper and in the readme file on how we obtained these results. If needed, I can try to summarize them again here.

Cheers,

Gilles

**Comment by horizonfly99** [comment]
Okay, thank you very much for your help
